// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prototype.Data;

#nullable disable

namespace prototype.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241202035533_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicInformation", b =>
                {
                    b.Property<int>("BASIC_INFO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BASIC_INFO_ID"));

                    b.Property<string>("ACCREDITATION_OF_SUBJECTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APPLICATION_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APPLYING_AS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BI_STUDENT_ACC_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURRENTLY_ENROLLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME_OF_SCHOOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_CAMPUS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_CAMPUS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_CAMPUS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_COURSE1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_COURSE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PREFERRED_COURSE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STRAND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRACK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BASIC_INFO_ID");

                    b.ToTable("BASIC_INFORMATION");
                });

            modelBuilder.Entity("prototype.Models.AccountCreationModel", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USERID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccStudentId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACC_STUDENT_ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ENROLLMENT_STATUS");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_TYPE");

                    b.Property<string>("Verification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VERIFICATION");

                    b.HasKey("AccountId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("prototype.Models.Register.Educations", b =>
                {
                    b.Property<int>("EDUCATION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EDUCATION_ID"));

                    b.Property<string>("COLLEGE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_COURSE_YR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_DATE_GRADUATED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_HONORS_RECEIVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_LOCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_SCHOOL_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("E_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HIGH_SCHOOL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_COURSE_YR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_CURRICULUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_DATE_GRADUATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_HONORS_RECEIVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_LOCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HS_SCHOOL_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TECH_VOC_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_COURSE_YR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_CURRICULUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_DATE_GRADUATED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_HONORS_RECEIVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_LOCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TV_SCHOOL_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EDUCATION_ID");

                    b.ToTable("EDUCATION");
                });

            modelBuilder.Entity("prototype.Models.Register.EmergencyContact", b =>
                {
                    b.Property<int>("PICOE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PICOE_ID"));

                    b.Property<string>("PICOE_BRGY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_CONTACTNUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_DISTRICT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_HOUSESTREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_MIDDLENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_MUNICIPALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_RELATIONSHIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_SUFFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PICOE_ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PICOE_ID");

                    b.ToTable("PERSON_INCASEOF_EMERGENCY");
                });

            modelBuilder.Entity("prototype.Models.Register.Family", b =>
                {
                    b.Property<int>("FAMILY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAMILY_ID"));

                    b.Property<string>("FAMILY_BARANGAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAMILY_DISTRICT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAMILY_MUNICIPALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAMILY_STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAMILY_ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_EDUCATIONAL_ATTAINMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_MIDDLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_OCCUPATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHER_SUFFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_MIDDLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_RELATIONSHIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUARDIAN_SUFFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_EDUCATIONAL_ATTAINMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_MIDDLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHER_OCCUPATION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FAMILY_ID");

                    b.ToTable("FAMILY");
                });

            modelBuilder.Entity("prototype.Models.Register.PersonalInformation", b =>
                {
                    b.Property<int>("PERSONAL_INFO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PERSONAL_INFO_ID"));

                    b.Property<string>("BARANGAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BIRTH_PLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITIZENSHIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CIVIL_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DATE_OF_BIRTH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTRICT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MIDDLE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUNICIPALITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELIGION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUFFIX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PERSONAL_INFO_ID");

                    b.ToTable("PERSONAL_INFORMATION");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Building", b =>
                {
                    b.Property<int>("Building_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Building_ID"));

                    b.Property<string>("Building_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Building_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Building_ID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Room", b =>
                {
                    b.Property<int>("Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_ID"));

                    b.Property<int>("Building_ID")
                        .HasColumnType("int");

                    b.Property<string>("Room_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Room_ID");

                    b.HasIndex("Building_ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SCHEDULE_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("Building")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BUILDING");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DAY");

                    b.Property<string>("LectureLab")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LECTURE_LAB");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROOM");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECTION");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUBJECT_CODE");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUBJECT_NAME");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIME");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TYPE");

                    b.Property<string>("YearSem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("YEAR_SEM");

                    b.HasKey("ScheduleId");

                    b.ToTable("SCHEDULE");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Section", b =>
                {
                    b.Property<int>("SECTION_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SECTION_ID"));

                    b.Property<string>("MAX_CAPACITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTION_SLOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTION_YEAR_SEM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SECTION_ID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("prototype.Models.Student.StudentEnlistment", b =>
                {
                    b.Property<int>("STUDENT_ENLISTMENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STUDENT_ENLISTMENT_ID"));

                    b.Property<byte[]>("SEF_ID_PICTURE")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SEF_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENT_ENLISTMENT_ID");

                    b.ToTable("STUDENT_ENLISTMENT");
                });

            modelBuilder.Entity("prototype.Models.Student.StudentReference", b =>
                {
                    b.Property<int>("STUDENT_REF_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STUDENT_REF_ID"));

                    b.Property<string>("DATE_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REFERENCE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SR_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENT_REF_ID");

                    b.ToTable("STUDENT_REFERENCE");
                });

            modelBuilder.Entity("prototype.Models.Student.StudentYrScreening", b =>
                {
                    b.Property<int>("STUDENT_YR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STUDENT_YR_ID"));

                    b.Property<string>("ACADEMIC_FROM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACADEMIC_TO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("APPLYING_AS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PROGRAMS_OFFER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYC_STUDENT_ACC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YR_LEVEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YR_TERM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STUDENT_YR_ID");

                    b.ToTable("STUDENT_YR_SCREENING");
                });

            modelBuilder.Entity("prototype.Models.StudentGrading", b =>
                {
                    b.Property<int>("GRADES_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRADES_ID"));

                    b.Property<string>("CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADES_STUDENT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GWA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOTAL_UNITS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNITS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GRADES_ID");

                    b.ToTable("STUDENT_GRADES");
                });

            modelBuilder.Entity("prototype.Models.User", b =>
                {
                    b.Property<int>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USERID"));

                    b.Property<string>("ACC_STUDENT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENROLLMENT_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERIFICATION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USERID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Room", b =>
                {
                    b.HasOne("prototype.Models.Registrar.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("Building_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("prototype.Models.Registrar.Building", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
